# Building Predictive Models

In [1]:
import pandas as pd
import os
import numpy as np

## Import Data

In [2]:
# set the path of the processed data
processed_data_path = os.path.join(os.path.pardir, 'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [3]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Survived            891 non-null    int64  
 1   Age                 891 non-null    float64
 2   Fare                891 non-null    float64
 3   FamilySize          891 non-null    int64  
 4   IsMother            891 non-null    int64  
 5   IsMale              891 non-null    int64  
 6   Deck_A              891 non-null    int64  
 7   Deck_B              891 non-null    int64  
 8   Deck_C              891 non-null    int64  
 9   Deck_D              891 non-null    int64  
 10  Deck_E              891 non-null    int64  
 11  Deck_F              891 non-null    int64  
 12  Deck_G              891 non-null    int64  
 13  Deck_Z              891 non-null    int64  
 14  Pclass_1            891 non-null    int64  
 15  Pclass_2            891 non-null    int64  
 16  Pclass_3

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 418 non-null    float64
 1   Fare                418 non-null    float64
 2   FamilySize          418 non-null    int64  
 3   IsMother            418 non-null    int64  
 4   IsMale              418 non-null    int64  
 5   Deck_A              418 non-null    int64  
 6   Deck_B              418 non-null    int64  
 7   Deck_C              418 non-null    int64  
 8   Deck_D              418 non-null    int64  
 9   Deck_E              418 non-null    int64  
 10  Deck_F              418 non-null    int64  
 11  Deck_G              418 non-null    int64  
 12  Deck_Z              418 non-null    int64  
 13  Pclass_1            418 non-null    int64  
 14  Pclass_2            418 non-null    int64  
 15  Pclass_3            418 non-null    int64  
 16  Title

## Data Preperation

In [6]:
X = train_df.loc[:,'Age':].values
y = train_df['Survived'].ravel()

In [7]:
print(X.shape, y.shape)

(891, 32) (891,)


In [8]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [9]:
# average survival in train and test
print('mean survival in train: {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test: {0:.3f}'.format(np.mean(y_test)))

mean survival in train: 0.383
mean survival in test: 0.385


### Check Scikit-Learn Version

In [10]:
import sklearn

In [11]:
sklearn.__version__

'1.2.1'

In [12]:
# !conda update -y scikit-learn

## Baseline Model

In [13]:
# import function
from sklearn.dummy import DummyClassifier

In [14]:
# create model
model_dummy = DummyClassifier(strategy = 'most_frequent', random_state=0)

In [15]:
# train model
model_dummy.fit(X_train, y_train)

DummyClassifier(random_state=0, strategy='most_frequent')

In [16]:
print('score for baseline model: {0:.2f}'.format(model_dummy.score(X_test, y_test))) #accuracy

score for baseline model: 0.61


In [17]:
# performance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [18]:
# accuracy score
print('accuracy for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

accuracy for baseline model: 0.61


In [19]:
# confusion matrix 
print('confusion matrix for baseline model: \n{0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test))))
#           predicted neg | predicted pos
# actual neg |            |
# actual pos |            |

confusion matrix for baseline model: 
[[110   0]
 [ 69   0]]


In [20]:
# precision and recall scores
print('precision for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))
print('recall for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))

precision for baseline model: 0.00
recall for baseline model: 0.00


C:\Users\molly\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## First Kaggle Submission 

In [21]:
# converting to the matrix
test_X = test_df.values

In [22]:
# get preditions
predictions = model_dummy.predict(test_X)

In [23]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})

In [24]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [25]:
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(submission_data_path, '01_dummy.csv')

In [26]:
df_submission.to_csv(submission_file_path, index=False)

In [27]:
def get_submission_file(model, filename):
    # converting to the matrix
    test_X = test_df.values
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})
    # submission file
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)
    df_submission.to_csv(submission_file_path, index=False)

In [28]:
# can use function to get submission file
# get_submission_file(model_dummy, '01_dummy.csv')

## Logistic Regresson Model

In [29]:
# import function
from sklearn.linear_model import LogisticRegression

In [30]:
# create model
model_lr_1 = LogisticRegression(random_state=0, max_iter=1000)

In [31]:
# train model
model_lr_1.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [32]:
# evaluate model
print('score for logistic regression - version 1: {0:.2f}'.format(model_lr_1.score(X_test, y_test)))

score for logistic regression - version 1: 0.83


In [33]:
# performance metrics
# accuracy
print('accuracy for logisitc regression - version 1: {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
# confusion matrix
print('confusion matric for logistic regression - version 1: \n{0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test))))
# precision
print('precision for logistic regression - version 1: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))
# recall
print('recall for logistic regression - version 1: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))

accuracy for logisitc regression - version 1: 0.83
confusion matric for logistic regression - version 1: 
[[95 15]
 [15 54]]
precision for logistic regression - version 1: 0.78
recall for logistic regression - version 1: 0.78


In [34]:
# model coefficients
model_lr_1.coef_

array([[-0.03276711,  0.00421876, -0.52733595,  0.63699268, -1.11412545,
        -0.0150662 , -0.30334925, -0.52664552,  0.40182895,  0.97395254,
         0.27882138, -0.28393201, -0.51623575,  0.59061638,  0.13274977,
        -0.71399201,  0.23388533,  1.09438857,  0.15252857, -1.5576445 ,
         0.7370857 , -0.1559653 , -0.49490422, -0.11963673, -0.03973287,
         0.00537623,  0.16336753,  0.12371221,  0.11645044, -0.2307885 ,
        -0.17753145,  0.1869056 ]])

## Second Kaggle Submission

In [35]:
# get submission file
get_submission_file(model_lr_1, '02_lr.csv')

## Part 2

## Hyperparameter Optimization

In [36]:
# base model
model_lr = LogisticRegression(random_state=0, max_iter=5000)

In [37]:
from sklearn.model_selection import GridSearchCV

In [38]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l2']}
clf = GridSearchCV(model_lr, param_grid = parameters, cv = 3)

In [39]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=LogisticRegression(max_iter=5000, random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l2']})

In [40]:
clf.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [41]:
print('best score: {0:.2f}'.format(clf.best_score_))

best score: 0.83


In [42]:
# evaluate model
print('score for logisitic regression - version 2: {0:.2f}'.format(clf.score(X_test, y_test)))

score for logisitic regression - version 2: 0.83


In [43]:
# get submission file
get_submission_file(clf, '03_lr.csv')

## Feature Normalization and Standardization

In [44]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### Feature Normalization

In [45]:
# feature normalization
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [46]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [47]:
# normalize test data
X_test_scaled = scaler.transform(X_test)

### Feature Standardization

In [48]:
# feature standardization -> mean = 0 and unit variance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [49]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(-2.143955101825949, 3.8031127012897366)

In [50]:
# normalize test data
X_test_scaled = scaler.transform(X_test)

### Create model after standardization

In [51]:
# base model
model_lr = LogisticRegression(random_state=0)
parameters = {'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l2']})

In [52]:
clf.best_score_

0.8089978607476747

In [53]:
# evaluate model
print('score for logistic regression - version 2: {0:.2f}'.format(clf.score(X_test_scaled, y_test)))

score for logistic regression - version 2: 0.84


## Model Persistence

In [54]:
# import pickle library
import pickle

In [55]:
# create the file paths
model_file_path = os.path.join(os.path.pardir, 'models', 'lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir, 'models', 'lr_scaler.pkl')

In [56]:
# open the files to write
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [57]:
# persist the model and scaler
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [58]:
# close the file
model_file_pickle.close()
scaler_file_pickle.close()

### load the persisted file

In [59]:
# open files in read mode
model_file_pickle = open(model_file_path, 'rb')
scaler_file_pickle = open(scaler_file_path, 'rb')
# load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
# close files
model_file_pickle.close()
scaler_file_pickle.close()

In [60]:
clf_loaded

GridSearchCV(cv=3, estimator=LogisticRegression(random_state=0),
             param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0],
                         'penalty': ['l2']})

In [61]:
scaler_loaded

StandardScaler()

In [62]:
# transform the test data using the loaded scaler object
X_test_scaled = scaler_loaded.transform(X_test)
# calculate the score using loaded model object
print('score for persisted logistic regression : {0:.2f}'.format(clf_loaded.score(X_test_scaled, y_test)))

score for persisted logistic regression : 0.84
